Document: amarokfs
Title: Debian amarokfs Manual
Author: <insert document author here>
Abstract: This manual describes what amarokfs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amarokfs/amarokfs.sgml.gz

Format: postscript
Files: /usr/share/doc/amarokfs/amarokfs.ps.gz

Format: text
Files: /usr/share/doc/amarokfs/amarokfs.text.gz

Format: HTML
Index: /usr/share/doc/amarokfs/html/index.html
Files: /usr/share/doc/amarokfs/html/*.html

  
